<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
	  <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <RootNamespace>Shared</RootNamespace>
  </PropertyGroup>
	
	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
		<PackageReference Include="System.Memory" Version="4.5.5" />
	</ItemGroup>

</Project>
